<?php
/*
 * Made By: Siddharth Panchal & Dylan Burnham
 * 
 * File Name: quiz.php
 * 
 * Description: This is where quiz gets displayed  
 */
session_start();
include("db.php");

$isAdmin = 0; // Is user Admin?
$output = "";
$mid = 0;
$now = date('Y-m-d H:i:s');
$username = "";

if(isset($_SESSION['u_name']))
{
	// Check is user is logged in.
	$query = $db->prepare("SELECT * FROM quiz_member WHERE username = :username");
	$query->bindParam(":username",$_SESSION['u_name']);
	$query->execute();
	
	$query->setFetchMode(PDO::FETCH_OBJ);
	$result = $query->fetch();
	
	if($result->logged == 0)
		header("location: index.php");
	
	$mid = $result->mid;
	$username = $result->username;
	
	if($result->type == 1)
		$isAdmin = 1;
		
	//User Create New Catagory
	
}
else
{
	header("location: index.php");
}

include("class/template.php");

$scripts = array("main.js","member.js","quiz.js");
$styles = array("main.css","forms.css");

$template = new Template("QuizBuilder - Easier to Build Quiz", $scripts, $styles);

$template->outPutHeader();

$template->headerBlock(1);

$template->navigationBlockLogged($isAdmin);

//$template->sidebarBlock($isAdmin);
?>

<article id="content">
<?php
if(!isset($_GET['id']))
	header("location: index.php");

// Get quiz by its id
$id = mysql_real_escape_string(stripslashes(trim($_GET['id'])));

$catagory = $db->prepare("SELECT * FROM quiz_catagory WHERE cid=$id");
$catagory->execute();
$catagory->setFetchMode(PDO::FETCH_OBJ);
$getCat = $catagory->fetch();

// This part is criticle, main.js has a function which get data from json file generated by genXML.php and insert into mainQuiz id.
?>
<input id="hiddenID" type="hidden" value="<?php echo $id; ?>">
<h2>Quiz Title: <?php echo $getCat->title; ?></h2>
	<div id="mainquiz">
    	
    </div>

</article>

<?php $template->outputFooter(); ?>